"""index user_id  urls via pgadmin

Revision ID: 08037d85619e
Revises: f12b5e21e107
Create Date: 2025-01-21 13:13:01.768936

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08037d85619e'
down_revision: Union[str, None] = 'f12b5e21e107'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_url_shortener_user_id', 'url_shortener', ['user_id'], unique=False)
  
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
      op.drop_index('idx_url_shortener_user_id', table_name='url_shortener')
    # ### end Alembic commands ###
