"""user columns updated at

Revision ID: 21ed3ff8a133
Revises: 5961e0429a67
Create Date: 2025-01-24 12:21:42.553838

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21ed3ff8a133'
down_revision: Union[str, None] = '5961e0429a67'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('userss', sa.Column('updated_at', sa.TIMESTAMP(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('userss', 'updated_at')
    # ### end Alembic commands ###
