"""short code password field

Revision ID: 37c1d49e1f92
Revises: bfb66a514807
Create Date: 2025-01-20 23:06:55.596416

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '37c1d49e1f92'
down_revision: Union[str, None] = 'bfb66a514807'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('url_shortener', sa.Column('password', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('url_shortener', 'password')
    # ### end Alembic commands ###
