"""user columns for signup login

Revision ID: 5961e0429a67
Revises: f12b5e21e107
Create Date: 2025-01-24 12:15:09.102933

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5961e0429a67'
down_revision: Union[str, None] = 'f12b5e21e107'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('userss', sa.Column('password_hash', sa.String(length=255), nullable=True))
    op.add_column('userss', sa.Column('user_inactive', sa.TIMESTAMP(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('userss', 'user_inactive')
    op.drop_column('userss', 'password_hash')
    # ### end Alembic commands ###
