"""foreign key user_id in url_shortener

Revision ID: 6076bfce55f0
Revises: 8d574ba5a31c
Create Date: 2025-01-18 17:40:32.794149

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6076bfce55f0'
down_revision: Union[str, None] = '8d574ba5a31c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('url_shortener', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'url_shortener', 'userss', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'url_shortener', type_='foreignkey')
    op.drop_column('url_shortener', 'user_id')
    # ### end Alembic commands ###
