"""fix enum type

Revision ID: 801cf01b182d
Revises: 21ed3ff8a133
Create Date: 2025-01-25 18:45:12.754844

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '801cf01b182d'
down_revision: Union[str, None] = '21ed3ff8a133'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE \"TierLevel\" RENAME TO tierlevel;")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE tierlevel RENAME TO \"TierLevel\";")
    # ### end Alembic commands ###
