"""Add users table and link to url_shortener

Revision ID: 98d93e78d699
Revises: f0434c553e78
Create Date: 2025-01-18 12:01:36.284471

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '98d93e78d699'
down_revision: Union[str, None] = 'f0434c553e78'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=True),
    sa.Column('api_key', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('api_key'),
    sa.UniqueConstraint('email')
    )
    # op.add_column('url_shortener', sa.Column('user_id', sa.Integer(), nullable=False))
    op.drop_index('idx_url_shortener_analytics', table_name='url_shortener')
    # op.create_foreign_key(None, 'url_shortener', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_constraint(None, 'url_shortener', type_='foreignkey')
    op.create_index('idx_url_shortener_analytics', 'url_shortener', ['created_at', 'visit_count', 'short_code'], unique=False)
    # op.drop_column('url_shortener', 'user_id')
    op.drop_table('users')
    # ### end Alembic commands ###
