"""column tier level users 

Revision ID: bfb66a514807
Revises: 908616e8fb66
Create Date: 2025-01-20 17:21:45.143213

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import Enum


# revision identifiers, used by Alembic.
revision: str = 'bfb66a514807'
down_revision: Union[str, None] = '908616e8fb66'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    tier_level_enum = sa.Enum('HOBBY', 'ENTERPRISE', name='TierLevel')
    tier_level_enum.create(op.get_bind())
    op.add_column('userss', sa.Column('tier_level',tier_level_enum, nullable=False,server_default='HOBBY'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('userss', 'tier_level')

    sa.Enum('HOBBY', 'ENTERPRISE', name='TierLevel').drop(op.get_bind())
    # ### end Alembic commands ###
