"""Add visit_cnt and last_accessed_at columns

Revision ID: f0434c553e78
Revises: 
Create Date: 2025-01-17 00:26:27.721221

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f0434c553e78'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('url_shortener', sa.Column('visit_cnt', sa.Integer(),server_default=sa.text('0'), nullable=False))
    op.add_column('url_shortener', sa.Column('last_accessed_at', sa.TIMESTAMP(), nullable=True))
    # op.drop_index('idx_url_shortener_analytics', table_name='url_shortener')
    # op.drop_column('url_shortener', 'visit_count')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('url_shortener', sa.Column('visit_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False))
    # op.create_index('idx_url_shortener_analytics', 'url_shortener', ['created_at', 'visit_count', 'short_code'], unique=False)
    op.drop_column('url_shortener', 'last_accessed_at')
    op.drop_column('url_shortener', 'visit_cnt')
    # ### end Alembic commands ###
