"""short code password field

Revision ID: f12b5e21e107
Revises: 37c1d49e1f92
Create Date: 2025-01-20 23:06:55.596416

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f12b5e21e107'
down_revision: Union[str, None] = '37c1d49e1f92'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    pass
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('url_shortener', sa.Column('password', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    pass
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_column('url_shortener', 'password')
    # ### end Alembic commands ###
